// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-about'
  | 'pref-s2-key'
  | 'pref-s2-key-help'
  | 'pref-source'
  | 'pref-source-help'
  | 'pref-source-openalex'
  | 'pref-source-s2'
  | 'pref-source-title'
  | 'pref-target-parent'
  | 'pref-target-root'
  | 'pref-target-selected'
  | 'pref-target-title'
  | 'pref-title'
  | 'section-header'
  | 'section-sidenav';
