// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-about'
  | 'pref-s2-key'
  | 'pref-s2-key-help'
  | 'pref-title'
  | 'section-header'
  | 'section-sidenav';
